version: '3'

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8010:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
