# CircleCI configuration

version: 2.1

executors:
  my_executor:
    docker:
      - image: circleci/php:7.2

commands:
  update_php:
    description: "DockerイメージのPHPアップデート"
    steps:
      - setup_remote_docker
      - run:
          name: install redis extension
          command: |
            sudo pecl install -o -f redis
            sudo rm -rf /tmp/pear
            sudo docker-php-ext-enable redis

jobs:
  build_dev:
    working_directory: ~/workspace

    executor: my_executor

    steps:
      - checkout
      - update_php

      - restore_cache:
          keys:
            - composer-dev-{{ checksum "composer.lock" }}
            - composer-

      - run:
          name: Composer install (with require-dev)
          command: |
            composer config http-basic.m-p.backlog.jp $BACKLOG_USER $BACKLOG_PASSWORD
            composer install --dev -n --prefer-dist

      - save_cache:
          key: composer-dev-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - persist_to_workspace:
          root: .
          paths:
            - .

  analysis:
    working_directory: ~/workspace
    executor: my_executor

    steps:
      - attach_workspace:
          at: .

      - run:
          name: create .env file
          command: echo $ANALYSIS_DOTENV | base64 --decode > .env

      # 確認用
      # - store_artifacts:
      #     path: ./.env

      - run:
          name: PHP CodeSniffer
          command: composer phpcs

      - run:
          name: PHPStan
          command: composer phpstan > ./report/phpstan_result.txt

      - store_artifacts:
          path: ./report

      - run:
          name: remove .env file
          command: rm -v ./.env

workflows:
  version: 2

  analysis:
    jobs:
      - build_dev
      - analysis:
          requires:
            - build_dev
